### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by jg-24** [wouterdebie/locast2tuner#94]
Been running on 0.1.53 (installed with brew running in terminal) since Aug 16, and this morning while streaming the locast login failed:
```
Aug 25 09:23:54.202 INFO Stream 1936e80 - added segment "https://hls.locastnet.org/proxy/sea/king_src271651454.ts"
Aug 25 09:23:54.202 INFO Serving https://hls.locastnet.org/proxy/sea/king_src271651446.ts (6 s) in 5.4179688s
Aug 25 09:23:57.704 INFO Login token expired: Mutex { is_locked: true, has_waiters: false }
Aug 25 09:23:57.704 INFO Logging in with ...
thread 'main' panicked at 'Login failed', src/credentials.rs:72:9
```

Upgraded to latest with same result:
```
Aug 25 09:28:17.439 INFO locast2tuner 0.3.4 on Darwin 20.6.0 starting..
Aug 25 09:28:17.439 INFO Consider sponsoring this project at https://github.com/sponsors/wouterdebie!
thread 'main' panicked at 'Login failed', src/credentials.rs:72:9
```

**Steps To Reproduce**
1. Run application
2. See log output above

** Logs **
Inline above

** Configuration **
```
username="[username]"
password="[password]"
tuner_count=5
multiplex = true
bind_address = "192.168.[n].[n]"
```

**Environment**
MacOS 11.5.2

**Comment by wouterdebie** [comment]
Locast.org just started enforcing the captcha.. We'll have to look for ways to deal with this.
